spring: 
   profiles: 
       active: 
       - dev
---
server: 
   port: 7001  #注册中心占用7001端口，冒号后面必须要有空格

spring: 
   profiles: dev
   application: 
       name: jerryServiceClound-config-eureka-client

eureka: 
    instance: 
       hostname: eureka7001.com  #冒号后面必须要有空格
    client: 
       register-with-eureka: false	 #不通过eureka获取注册信息
       service-url: 
          defaultZone: http://eureka7001.com:7001/eureka/
---
server: 
   port: 7001  #注册中心占用7001端口，冒号后面必须要有空格

spring: 
   profiles: test
   application: 
       name: jerryServiceClound-config-eureka-client

eureka: 
    instance: 
       hostname: eureka7001.com  #冒号后面必须要有空格
    client: 
       register-with-eureka: false	 #不通过eureka获取注册信息
       service-url: 
          defaultZone: http://eureka7001.com:7001/eureka/