spring: 
    profiles: 
        active: 
        - dev
---
server: 
   port: 8001
spring: 
    profiles: dev
    application: 
      name: jerryServiceClound-config-dept-client
    datasource: 
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/clounddb01
      username: root
      password: root
      dbcp2: 
          min-idle: 5
          initial-size: 5
          max-total: 5
          max-wait-millis: 200
mybatis: 
     config-location: classpath:mybatis/mybatis.cfg.xml
     type-aliases-package: com.jerry.springclound.entities
     mapper-locations: 
     - classpath: mybatis/mapper/**/*.xml

eureka: 
    client: #客户端注册进eureka服务列表
       service-url: 
          defaultZone: http://eureka7001.com:7001/eureka
     instance: 
        instance-id: dept-8001.com
        prefer-ip-address: true

info: 
   app.name: jerry-jerryServiceClound-springcloundconfig01
   company.name: www.jerrysjj.cn
   build.artifactId: $project.artifactId$
   build.version: $project.version$
---
server: 
   port: 8001
spring: 
    profiles: test
    application: 
      name: jerryServiceClound-config-dept-client
    datasource: 
      type: com.alibaba.druid.pool.DruidDataSource
      #driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/clounddb02
      username: root
      password: root
      dbcp2: 
          min-idle: 5
          initial-size: 5
          max-total: 5
          max-wait-millis: 200
mybatis: 
     config-location: classpath:mybatis/mybatis.cfg.xml
     type-aliases-package: com.jerry.springclound.entities
     mapper-locations: 
     - classpath: mybatis/mapper/**/*.xml

eureka: 
    client: #客户端注册进eureka服务列表
       service-url: 
          defaultZone: http://eureka7001.com:7001/eureka
     instance: 
        instance-id: dept-8001.com
        prefer-ip-address: true

info: 
   app.name: jerry-jerryServiceClound-springcloundconfig01
   company.name: www.jerrysjj.cn
   build.artifactId: $project.artifactId$
   build.version: $project.version$